CSV file and XLSX file

In [28]:
import pandas as pd

xlsx_path = 'movies_top_awards.xlsx'
df = pd.read_excel(xlsx_path)
# csv_path = 'movies_top_awards.csv'
# df = pd.read_csv(csv_path)
df.head()

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,Ben-Hur,1959,5,12,William Wyler,212,English
1,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
2,Titanic,1997,11,14,James Cameron,195,English
3,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
4,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"

1.Assign the DataFrame

In [42]:
# Oscar number and Nominations columns to the variable 'new'
new = df[['Oscar number', 'Nominations']]

# Language to the variable 'newer'
newer = df.drop(columns=['Language'])

new, newer

(    Oscar number  Nominations
 0              5           12
 1             11           11
 2             11           14
 3             10           11
 4              9           12
 5              9            9
 6              9            9
 7              8           11
 8              8           10
 9              8           13
 10             8           11
 11             8           13
 12             8           12
 13             8           12,
                                             Movie  Release  Oscar number  \
 0                                         Ben-Hur     1959             5
 1   The Lord of the Rings: The Return of the King     2003            11
 2                                         Titanic     1997            11
 3                                 West Side Story     1961            10
 4                             The English Patient     1996             9
 5                                            Gigi     1958             9
 6                                The Last Emperor     1987             9
 7                                         Amadeus     1984             8
 8                                         Cabaret     1972             8
 9                           From Here to Eternity     1953             8
 10                                         Gandhi     1982             8
 11                             Gone with the Wind     1939             8
 12                                   My Fair Lady     1964             8
 13                              On the Waterfront     1954             8

     Nominations                     Director  Duration (minutes)
 0            12                William Wyler                 212
 1            11                Peter Jackson                 201
 2            14                James Cameron                 195
 3            11  Robert Wise, Jerome Robbins                 152
 4            12            Anthony Minghella                  16
 5             9            Vincente Minnelli                 115
 6             9          Bernardo Bertolucci                 163
 7            11                 Milo≈° Forman                 161
 8            10                    Bob Fosse                 124
 9            13               Fred Zinnemann                 118
 10           11         Richard Attenborough                 191
 11           13               Victor Fleming                 221
 12           12                 George Cukor                 170
 13           12                   Elia Kazan                 108  )

2. Retrieve the rows of all the movies

In [117]:
# Duration longer than 200 minutes
long_duration_movies = df[df['Duration (minutes)'] > 200]

# Less than 12 Oscar nominations
less_than_12_nominations = df[df['Nominations'] < 12]

long_duration_movies, less_than_12_nominations
df

,Unnamed: 0,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,0,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
1,1,Titanic,1997,11,14,James Cameron,195,English
2,2,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
3,3,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
4,4,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
5,5,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
6,6,Amadeus,1984,8,11,Milo≈° Forman,161,English
7,7,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
8,8,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
9,9,Gandhi,1982,8,11,Richard Attenborough,191,English
10,10,Gone with the Wind,1939,8,13,Victor Fleming,221,English
11,11,My Fair Lady,1964,8,12,George Cukor,170,English
12,12,On the Waterfront,1954,8,12,Elia Kazan,108,English
13,13,The Lord of the Rings: The Fellowship of the Ring,2001,4,13,Peter Jackson,178,English

3. Access the 2nd row and the 3rd column.AND Access the columns named Release and Nominations.

In [48]:
# Access the 2nd row and 3rd column
sec_row_thi_clmn = df.iloc[1, 2]

rls_noms = df[['Release', 'Nominations']]

# Displaying the results
sec_row_thi_clmn, rls_noms

(11,
     Release  Nominations
 0      1959           12
 1      2003           11
 2      1997           14
 3      1961           11
 4      1996           12
 5      1958            9
 6      1987            9
 7      1984           11
 8      1972           10
 9      1953           13
 10     1982           11
 11     1939           13
 12     1964           12
 13     1954           12)

4. Access the value for the row with index 10 and the column name 'Director' AND Access the value for the row with the index 2 and the column name 'Release'

In [55]:
rowten = df.at[10, 'Director']
rowtwo = df.at[2, 'Release']

rowten, rowtwo

('Richard Attenborough', 1997)

5. Add a new row to the DataFrame

In [79]:
# Creating a new row with the specified values

# Index 5
df.loc[4.5] = ['The Silence of the Lambs', 1991, 5, 7, 'Jonathan Demme', 118, 'English']
df = df.sort_index().reset_index(drop=True)
print(df)

                                            Movie  Release  Oscar number  \
0                        The Silence of the Lambs     1991             5
1   The Lord of the Rings: The Return of the King     2003            11
2                                         Titanic     1997            11
3                                 West Side Story     1961            10
4                             The English Patient     1996             9
5                        The Silence of the Lambs     1991             5
6                        The Silence of the Lambs     1991             5
7                                The Last Emperor     1987             9
8                                         Amadeus     1984             8
9                                         Cabaret     1972             8
10                          From Here to Eternity     1953             8
11                                         Gandhi     1982             8
12                             Gone with the Wind     1939             8
13                                   My Fair Lady     1964             8
14                              On the Waterfront     1954             8
15                       The Silence of the Lambs     1991             5

    Nominations                     Director  Duration (minutes)  \
0             7               Jonathan Demme                 118
1            11                Peter Jackson                 201
2            14                James Cameron                 195
3            11  Robert Wise, Jerome Robbins                 152
4            12            Anthony Minghella                  16
5             7               Jonathan Demme                 118
6             7               Jonathan Demme                 118
7             9          Bernardo Bertolucci                 163
8            11                 Milo≈° Forman                 161
9            10                    Bob Fosse                 124
10           13               Fred Zinnemann                 118
11           11         Richard Attenborough                 191
12           13               Victor Fleming                 221
13           12                 George Cukor                 170
14           12                   Elia Kazan                 108
15            7               Jonathan Demme                 118

                            Language
0                            English
1                            English
2                            English
3                            English
4   English, German, Italian, Arabic
5                            English
6                            English
7        English, Mandarin, Japanese
8                            English
9                    English, German
10                           English
11                           English
12                           English
13                           English
14                           English
15                           English

In [81]:
# Removing the row with index 5
df = df.drop(index=0)

In [83]:
df

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
1,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
2,Titanic,1997,11,14,James Cameron,195,English
3,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
4,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
5,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
6,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
7,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
8,Amadeus,1984,8,11,Milo≈° Forman,161,English
9,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
10,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
11,Gandhi,1982,8,11,Richard Attenborough,191,English
12,Gone with the Wind,1939,8,13,Victor Fleming,221,English
13,My Fair Lady,1964,8,12,George Cukor,170,English
14,On the Waterfront,1954,8,12,Elia Kazan,108,English
15,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English

6.

In [87]:
df.loc[0] = ['The Lord of the Rings: The Fellowship of the Ring', 2001, 4, 13, 'Peter Jackson', 178, 'English']
df = df.sort_index().reset_index(drop=True)
df

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,The Lord of the Rings: The Fellowship of the Ring,2001,4,13,Peter Jackson,178,English
1,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
2,Titanic,1997,11,14,James Cameron,195,English
3,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
4,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
5,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
6,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
7,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
8,Amadeus,1984,8,11,Milo≈° Forman,161,English
9,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
10,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
11,Gandhi,1982,8,11,Richard Attenborough,191,English
12,Gone with the Wind,1939,8,13,Victor Fleming,221,English
13,My Fair Lady,1964,8,12,George Cukor,170,English
14,On the Waterfront,1954,8,12,Elia Kazan,108,English
15,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English

In [89]:
# Removing the row with index 15
df = df.drop(index=15)

In [91]:
df

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,The Lord of the Rings: The Fellowship of the Ring,2001,4,13,Peter Jackson,178,English
1,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
2,Titanic,1997,11,14,James Cameron,195,English
3,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
4,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
5,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
6,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
7,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
8,Amadeus,1984,8,11,Milo≈° Forman,161,English
9,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
10,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
11,Gandhi,1982,8,11,Richard Attenborough,191,English
12,Gone with the Wind,1939,8,13,Victor Fleming,221,English
13,My Fair Lady,1964,8,12,George Cukor,170,English
14,On the Waterfront,1954,8,12,Elia Kazan,108,English

In [93]:
# Removing the row with index 15, placed it in the wrong place
df = df.drop(index=0)
df

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
1,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
2,Titanic,1997,11,14,James Cameron,195,English
3,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
4,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
5,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
6,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
7,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
8,Amadeus,1984,8,11,Milo≈° Forman,161,English
9,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
10,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
11,Gandhi,1982,8,11,Richard Attenborough,191,English
12,Gone with the Wind,1939,8,13,Victor Fleming,221,English
13,My Fair Lady,1964,8,12,George Cukor,170,English
14,On the Waterfront,1954,8,12,Elia Kazan,108,English

In [95]:
df.loc[15] = ['The Lord of the Rings: The Fellowship of the Ring', 2001, 4, 13, 'Peter Jackson', 178, 'English']
df = df.sort_index().reset_index(drop=True)
df

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
1,Titanic,1997,11,14,James Cameron,195,English
2,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
3,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
4,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
5,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
6,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
7,Amadeus,1984,8,11,Milo≈° Forman,161,English
8,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
9,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
10,Gandhi,1982,8,11,Richard Attenborough,191,English
11,Gone with the Wind,1939,8,13,Victor Fleming,221,English
12,My Fair Lady,1964,8,12,George Cukor,170,English
13,On the Waterfront,1954,8,12,Elia Kazan,108,English
14,The Lord of the Rings: The Fellowship of the Ring,2001,4,13,Peter Jackson,178,English

In [97]:
# Removing the row with index 15, I have duplicates
df = df.drop(index=4)
df

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
1,Titanic,1997,11,14,James Cameron,195,English
2,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
3,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
5,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
6,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
7,Amadeus,1984,8,11,Milo≈° Forman,161,English
8,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
9,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
10,Gandhi,1982,8,11,Richard Attenborough,191,English
11,Gone with the Wind,1939,8,13,Victor Fleming,221,English
12,My Fair Lady,1964,8,12,George Cukor,170,English
13,On the Waterfront,1954,8,12,Elia Kazan,108,English
14,The Lord of the Rings: The Fellowship of the Ring,2001,4,13,Peter Jackson,178,English

7. Export the current version of your DataFrame as an Excel file with a new name

In [115]:
# Name of the file
df.to_excel('my_movies_data.xlsx', index=False)

print('Exported successfully.')

Exported successfully.

In [103]:
df

,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
1,Titanic,1997,11,14,James Cameron,195,English
2,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
3,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
5,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
6,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
7,Amadeus,1984,8,11,Milo≈° Forman,161,English
8,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
9,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
10,Gandhi,1982,8,11,Richard Attenborough,191,English
11,Gone with the Wind,1939,8,13,Victor Fleming,221,English
12,My Fair Lady,1964,8,12,George Cukor,170,English
13,On the Waterfront,1954,8,12,Elia Kazan,108,English
14,The Lord of the Rings: The Fellowship of the Ring,2001,4,13,Peter Jackson,178,English

In [111]:
#Checking if it exported and changed name
import pandas as pd
xlsx_path = 'my_movies_data.xlsx'
df = pd.read_excel(xlsx_path)
df

,Unnamed: 0,Movie,Release,Oscar number,Nominations,Director,Duration (minutes),Language
0,0,The Lord of the Rings: The Return of the King,2003,11,11,Peter Jackson,201,English
1,1,Titanic,1997,11,14,James Cameron,195,English
2,2,West Side Story,1961,10,11,"Robert Wise, Jerome Robbins",152,English
3,3,The English Patient,1996,9,12,Anthony Minghella,16,"English, German, Italian, Arabic"
4,4,The Silence of the Lambs,1991,5,7,Jonathan Demme,118,English
5,5,The Last Emperor,1987,9,9,Bernardo Bertolucci,163,"English, Mandarin, Japanese"
6,6,Amadeus,1984,8,11,Milo≈° Forman,161,English
7,7,Cabaret,1972,8,10,Bob Fosse,124,"English, German"
8,8,From Here to Eternity,1953,8,13,Fred Zinnemann,118,English
9,9,Gandhi,1982,8,11,Richard Attenborough,191,English
10,10,Gone with the Wind,1939,8,13,Victor Fleming,221,English
11,11,My Fair Lady,1964,8,12,George Cukor,170,English
12,12,On the Waterfront,1954,8,12,Elia Kazan,108,English
13,13,The Lord of the Rings: The Fellowship of the Ring,2001,4,13,Peter Jackson,178,English